# _config.yml

# Site settings
title: My Jekyll Site
description: >-
  A simple description of your site's purpose.
baseurl: "/publish" # replace with your actual repo name
url: "https://thekid2002.github.io" # replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima

# Include the _framework directory and other necessary files
include:
  - _framework
  - css
  - MyBlazorApp.styles.css
  - index.js
  - sample-data
