# _config.yml

# Site settings
title: My Jekyll Site
description: >- 
  A simple description of your site's purpose.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima

# Include the _framework directory
include:
  - _framework
  - MyBlazorApp.styles.css
